TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

# Note: the files in this directory were manually copied from the Hamamatsu DCAM SDK.

INC += dcamapi4.h
INC += dcamprop.h

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

